service: hindi-tts-lambda

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  timeout: 30
  memorySize: 1024

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: '{proxy+}'
          method: ANY

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false  # Changed to false to avoid needing Docker
    layer: false         # Optional: set to false for simpler packaging
    zip: true            # Optional: helps in local builds

package:
  exclude:
    - node_modules/**
    - .git/**
